### ISSUE TITLE
Transaction fees action - [BUG]

### ISSUE THREAD

**Issue by Haywayaheadshot** [Oniocha/Qargo-Ecommerce#16] opened 2023-09-29 13:47 UTC
### [BUG DESCRIPTION]
- When the user gets to the checkout page, they're supposed to get a fee quote from the backend. The backend does not get the amount from front end POST method.

### [SUGGESTED SOLUTION]
- Understand how the amount is destructed in the backend and what kind of response to expect.  That way, you can make proper requests and handle them appropriately.

**Comment by Haywayaheadshot** [comment] 2023-10-05 14:28
@DavidQuartz I think I get where this error is coming from. The API call in question from getting Flutterwave fee. I will read their API documentation to ensure I appropriately query it.

**Comment by DavidQuartz** [comment] 2023-10-05 15:49
@Haywayaheadshot closing this issue because it is caused by the way the client is making the request, which needs to be corrected. Also lets no open issues for bugs on feature branches which are not merged to main yet.

**Closed by DavidQuartz** 2023-10-05 15:49 UTC
Labels: bug
